services:
  - type: web
    name: uwhelper
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
